game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

game_admin_route:
    resource: "routing_admin.yml"
    prefix:   /admin

game_add_town:
    path:    /town/add
    defaults: { _controller: GameBundle:Town:add }

game_town:
    path:    /town
    defaults: { _controller: GameBundle:Town:index }

game_choice_town:
    path:    /town/choice/{id}
    defaults: { _controller: GameBundle:Town:choice }

game_building:
    path:    /building
    defaults: { _controller: GameBundle:Building:index }
game_building_infantry:
    path:    /b/i/{id}
    defaults: { _controller: GameBundle:Infantry:index }
game_academie:
    path:    /academie
    defaults: { _controller: GameBundle:Infantry:academie }

game_town_building_view:
    path:    /building/{id}
    defaults: { _controller: GameBundle:Building:view }
game_town_building_view_specific:
    path:    /building/s/{id}
    defaults: { _controller: GameBundle:Building:specific }
game_town_building_build:
    path:    /building/build/{id}
    defaults: { _controller: GameBundle:Building:build }

game_haut_conseil:
    path:    /clan
    defaults: { _controller: GameBundle:Clan:index}
game_clan_list:
    path:    /clan/list
    defaults: { _controller: GameBundle:Clan:list}
game_clan_create:
    path:    /clan/create
    defaults: { _controller: GameBundle:Clan:create }
game_clan_info:
    path:    /clan/info/{id}
    defaults: { _controller: GameBundle:Clan:info }